
version: 2

models:
  - name: fact_anime_analytics
    description: "This is fact table that contains all primary keys as foreign key."
    columns:
      - name: analytic_id
        description: "This is a primary key for fact_anime_analytics."
        tests:
          - not_null
          - unique

      - name: user_id
        description: "This is a primary key of dim_users table to build relationship with fact_anime_analytics."
        tests:
          - relationships:
              field: user_id
              to: ref('dim_users')

      - name: anime_id
        description: "This is a primary key of dim_animes table to build relationship with fact_anime_analytics."
        tests:
          - relationships:
              field: anime_id
              to: ref('dim_animes')

      - name: ur_id
        description: "This is a primary key of dim_rating table to build relationship with fact_anime_analytics."
        tests:
          - relationships:
              field: ur_id
              to: ref('dim_rating')